### ISSUE TITLE
Problem with running Symoro-bin

### ISSUE THREAD

**Issue by lyf2501** [symoro/symoro#13]
C:\Users\lyf2501>cd C:\Users\lyf2501\symoro-master

C:\Users\lyf2501\symoro-master>python setup.py develop
running develop
running egg_info
writing requirements to symoro.egg-info\requires.txt
writing symoro.egg-info\PKG-INFO
writing top-level names to symoro.egg-info\top_level.txt
writing dependency_links to symoro.egg-info\dependency_links.txt
reading manifest file 'symoro.egg-info\SOURCES.txt'
writing manifest file 'symoro.egg-info\SOURCES.txt'
running build_ext
Creating c:\python27\lib\site-packages\symoro.egg-link (link to .)
Removing symoro 0.2 from easy-install.pth file
Adding symoro 0.2 to easy-install.pth file
Installing symoro-bin.py script to C:\Python27\Scripts

Installed c:\users\lyf2501\symoro-master
Processing dependencies for symoro==0.2
Searching for PyOpenGL==3.1.0
Best match: PyOpenGL 3.1.0
Adding PyOpenGL 3.1.0 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for wxPython==4.0.0b2
Best match: wxPython 4.0.0b2
Adding wxPython 4.0.0b2 to easy-install.pth file
Installing wxdemo-script.py script to C:\Python27\Scripts
Installing wxdemo.exe script to C:\Python27\Scripts
Installing wxdemo.exe.manifest script to C:\Python27\Scripts
Installing img2png-script.py script to C:\Python27\Scripts
Installing img2png.exe script to C:\Python27\Scripts
Installing img2png.exe.manifest script to C:\Python27\Scripts
Installing pyslices-script.py script to C:\Python27\Scripts
Installing pyslices.exe script to C:\Python27\Scripts
Installing pyslices.exe.manifest script to C:\Python27\Scripts
Installing img2py-script.py script to C:\Python27\Scripts
Installing img2py.exe script to C:\Python27\Scripts
Installing img2py.exe.manifest script to C:\Python27\Scripts
Installing pyslicesshell-script.py script to C:\Python27\Scripts
Installing pyslicesshell.exe script to C:\Python27\Scripts
Installing pyslicesshell.exe.manifest script to C:\Python27\Scripts
Installing wxget-script.py script to C:\Python27\Scripts
Installing wxget.exe script to C:\Python27\Scripts
Installing wxget.exe.manifest script to C:\Python27\Scripts
Installing helpviewer-script.py script to C:\Python27\Scripts
Installing helpviewer.exe script to C:\Python27\Scripts
Installing helpviewer.exe.manifest script to C:\Python27\Scripts
Installing pyshell-script.py script to C:\Python27\Scripts
Installing pyshell.exe script to C:\Python27\Scripts
Installing pyshell.exe.manifest script to C:\Python27\Scripts
Installing pycrust-script.py script to C:\Python27\Scripts
Installing pycrust.exe script to C:\Python27\Scripts
Installing pycrust.exe.manifest script to C:\Python27\Scripts
Installing wxdocs-script.py script to C:\Python27\Scripts
Installing wxdocs.exe script to C:\Python27\Scripts
Installing wxdocs.exe.manifest script to C:\Python27\Scripts
Installing pywxrc-script.py script to C:\Python27\Scripts
Installing pywxrc.exe script to C:\Python27\Scripts
Installing pywxrc.exe.manifest script to C:\Python27\Scripts
Installing img2xpm-script.py script to C:\Python27\Scripts
Installing img2xpm.exe script to C:\Python27\Scripts
Installing img2xpm.exe.manifest script to C:\Python27\Scripts

Using c:\python27\lib\site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using c:\python27\lib\site-packages
Searching for sympy==0.7.3
Best match: sympy 0.7.3
Processing sympy-0.7.3-py2.7.egg
sympy 0.7.3 is already the active version in easy-install.pth
Installing isympy script to C:\Python27\Scripts

Using c:\python27\lib\site-packages\sympy-0.7.3-py2.7.egg
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using c:\python27\lib\site-packages
Finished processing dependencies for symoro==0.2

C:\Users\lyf2501\symoro-master>symoro-bin.py
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:523: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_new)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:528: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_open)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:533: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_save)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:538: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_save_as)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:542: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_pref)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:548: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  file_menu.AppendItem(m_exit)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:558: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  geom_menu.AppendItem(m_trans_matrix)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:563: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  geom_menu.AppendItem(m_fast_dgm)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:568: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  geom_menu.AppendItem(m_igm_paul)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:573: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  geom_menu.AppendItem(m_igm_pieper)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:578: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  geom_menu.AppendItem(m_geom_constraint)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:586: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_jac_matrix)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:591: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_determinant)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:596: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_vel)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:601: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_acc)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:606: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_jpqp)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:612: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  kin_menu.AppendItem(m_kin_constraint)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:620: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  dyn_menu.AppendItem(m_idym)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:625: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  dyn_menu.AppendItem(m_inertia_matrix)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:630: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  dyn_menu.AppendItem(m_h_term)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:635: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  dyn_menu.AppendItem(m_ddym)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:643: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  iden_menu.AppendItem(m_dyn_iden_model)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:651: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  iden_menu.AppendItem(m_base_inertial_params)
c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py:669: wxPyDeprecationWarning: Call to deprecated item. Use Append instead.
  viz_menu.AppendItem(m_viz)
Traceback (most recent call last):
  File "C:\Python27\Scripts\symoro-bin.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "C:\Users\lyf2501\symoro-master\bin\symoro-bin.py", line 38, in <module>
    main()
  File "C:\Users\lyf2501\symoro-master\bin\symoro-bin.py", line 31, in main
    style=style
  File "c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py", line 56, in __init__
    self.create_ui()
  File "c:\python27\lib\site-packages\symoro-0.2-py2.7.egg\symoroui\layout.py", line 279, in create_ui
    szr_link.AddSpacer((4,4))
TypeError: BoxSizer.AddSpacer(): argument 1 has unexpected type 'tuple'

Hi, developer,

I just install the symoro but I get this error message when I am trying to run symoro-bin; I can't find any problem with installation as you can see below:
I have 
wxPython == 4.0.0b2; 
PyOpenGL==3.1.0; 
numpy==1.13.3; 
sympy == 0.7.3
as I am researching into related TypeError: BoxSizer.AddSpacer(): argument 1 has unexpected type 'tuple'
it seems like in the latest wxPython; some functions are depreciated; so which version of wxPython can be used?

**Comment by lyf2501** [comment]
I solved this problem by replacing BoxSizer.AddSpacer(4), then the program runs; however, there are still other problems such as creating new robot with wxpython 4.0.2b1; so you are better off reinstall older version of wx

**Comment by dwadelinjianxiong** [comment]
hi lyf2501,
I'd like to ask which version of wxpython you installed to make it work. I tried 2.8.12.1 but failed, it can't detect by pip list, is there anything I missed after installing it?
